name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-and-setup-go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8

  test-and-scan:
    name: Test and Scan
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-and-setup-go
      
      - name: Run unit tests
        run: |
          go test -coverprofile=./cov.out ./...
      
      # gosec takes some time to run and is annoying on PRs, commenting it out for now
      # when re-enabling it, uncomment the following lines AND the sonar-project.properties entry for gosec
      # - name: Run Gosec Security Scanner
      #   uses: securego/gosec@6be2b51fd78feca86af91f5186b7964d76cb1256 # v2.22.10
      #   with:
      #     args: -no-fail -fmt=sonarqube -out gosec.json ./...
      
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}